const envelope = (schema) => ({ type: 'object', required: ['data', 'meta'], properties: { data: schema, meta: { $ref: '#/components/schemas/Meta' } } });
const errorEnvelope = { type: 'object', required: ['error', 'meta'], properties: { error: { $ref: '#/components/schemas/Error' }, meta: { $ref: '#/components/schemas/Meta' } } };
const response = (description, schema) => ({ description, content: { 'application/json': { schema: envelope(schema) } } });
const problem = (description) => ({ description, content: { 'application/json': { schema: errorEnvelope } } });

const openApiDocument = {
  openapi: '3.0.3',
  info: { title: 'FarmEase Core API', version: '0.2.0', description: 'Normalized agricultural intelligence APIs. Core v1 never substitutes simulated weather or market records for an unavailable provider.' },
  servers: [{ url: '/api/v1', description: 'FarmEase backend' }],
  tags: [{ name: 'System' }, { name: 'Providers' }, { name: 'Weather' }, { name: 'Markets' }, { name: 'Intelligence' }, { name: 'Geospatial' }, { name: 'Alerts' }],
  paths: {
    '/health': { get: { tags: ['System'], summary: 'Core health and default providers', responses: { 200: response('Service health', { $ref: '#/components/schemas/Health' }) } } },
    '/providers': { get: { tags: ['Providers'], summary: 'Registered provider capabilities and configuration status', responses: { 200: response('Providers', { type: 'array', items: { $ref: '#/components/schemas/Provider' } }) } } },
    '/weather/current': { get: { tags: ['Weather'], summary: 'Current normalized weather', parameters: [{ $ref: '#/components/parameters/Latitude' }, { $ref: '#/components/parameters/Longitude' }, { $ref: '#/components/parameters/WeatherProvider' }], responses: { 200: response('Current weather', { $ref: '#/components/schemas/CurrentWeather' }), 400: problem('Invalid request or provider selection'), 503: problem('Provider unavailable'), 504: problem('Provider timeout') } } },
    '/weather/forecast': { get: { tags: ['Weather'], summary: 'Normalized weather forecast', parameters: [{ $ref: '#/components/parameters/Latitude' }, { $ref: '#/components/parameters/Longitude' }, { $ref: '#/components/parameters/WeatherProvider' }], responses: { 200: response('Forecast days', { type: 'array', items: { $ref: '#/components/schemas/ForecastDay' } }), 400: problem('Invalid request or provider selection'), 503: problem('Provider unavailable'), 504: problem('Provider timeout') } } },
    '/markets': { get: { tags: ['Markets'], summary: 'Live normalized AGMARKNET market prices', parameters: [{ $ref: '#/components/parameters/MarketProvider' }, { $ref: '#/components/parameters/Commodity' }, { $ref: '#/components/parameters/State' }, { $ref: '#/components/parameters/District' }, { $ref: '#/components/parameters/Market' }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Offset' }], responses: { 200: response('Price records; an empty list is a valid real result', { type: 'array', items: { $ref: '#/components/schemas/MarketPrice' } }), 400: problem('Invalid request or provider selection'), 502: problem('Provider returned invalid data'), 503: problem('Provider unavailable or unconfigured'), 504: problem('Provider timeout') } } },
    '/market-prices': { get: { tags: ['Markets'], summary: 'Alias of /markets', parameters: [{ $ref: '#/components/parameters/MarketProvider' }, { $ref: '#/components/parameters/Commodity' }, { $ref: '#/components/parameters/State' }, { $ref: '#/components/parameters/District' }, { $ref: '#/components/parameters/Market' }, { $ref: '#/components/parameters/Limit' }, { $ref: '#/components/parameters/Offset' }], responses: { 200: response('Price records', { type: 'array', items: { $ref: '#/components/schemas/MarketPrice' } }), 400: problem('Invalid request or provider selection'), 502: problem('Provider returned invalid data'), 503: problem('Provider unavailable or unconfigured'), 504: problem('Provider timeout') } } },
    '/advisories': { post: { tags: ['Intelligence'], summary: 'Generate explainable farm advisories', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AdvisoryInput' } } } }, responses: { 200: response('Advisories and provenance', { $ref: '#/components/schemas/AdvisoryResult' }), 400: problem('Invalid farm context or provider selection'), 503: problem('Advisory engine unavailable') } } },
    '/crop-recommendation': { post: { tags: ['Intelligence'], summary: 'Crop recommendation', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CropInput' } } } }, responses: { 200: response('Recommendation with model provenance', { $ref: '#/components/schemas/CropRecommendation' }), 400: problem('Invalid crop input'), 503: problem('Intelligence service unavailable') } } },
    '/plant-diagnosis': { post: { tags: ['Intelligence'], summary: 'Diagnose a plant image', requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: ['file'], properties: { file: { type: 'string', format: 'binary', description: 'JPEG, PNG, or WebP; max 10 MB' } } } } } }, responses: { 200: response('Diagnosis', { $ref: '#/components/schemas/PlantDiagnosis' }), 400: problem('Invalid image'), 503: problem('Intelligence service unavailable') } } }
    ,'/farms/{id}/field-health': { get: { tags: ['Geospatial'], summary: 'Get normalized vegetation observations for a farm', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }, { in: 'query', name: 'provider', schema: { type: 'string', example: 'sentinel-2' } }], responses: { 200: response('Field health', { $ref: '#/components/schemas/FieldHealth' }), 404: problem('Farm not found'), 503: problem('Satellite provider unavailable') } } },
    '/alert-rules': { post: { tags: ['Alerts'], summary: 'Create an in-memory alert rule', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/AlertRule' } } } }, responses: { 201: response('Alert rule', { $ref: '#/components/schemas/AlertRule' }), 400: problem('Invalid alert rule') } } },
    '/farms/{id}/alerts/evaluate': { post: { tags: ['Alerts'], summary: 'Evaluate deterministic alerts for a farm', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { farm: { $ref: '#/components/schemas/Farm' }, weather: { type: 'object' }, marketPrices: { type: 'array', items: { $ref: '#/components/schemas/MarketPrice' } }, fieldHealth: { $ref: '#/components/schemas/FieldHealth' }, rules: { type: 'array', items: { $ref: '#/components/schemas/AlertRule' } } } } } } }, responses: { 200: response('Alert evaluation', { $ref: '#/components/schemas/AlertEvaluation' }), 400: problem('Invalid context or rules') } } },
    '/farms/{id}/alerts': { get: { tags: ['Alerts'], summary: 'List active alerts', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { 200: response('Active alerts', { type: 'array', items: { $ref: '#/components/schemas/Alert' } }) } } }
  },
  components: {
    parameters: {
      Latitude: { in: 'query', name: 'lat', required: true, schema: { type: 'number', minimum: -90, maximum: 90 } }, Longitude: { in: 'query', name: 'lon', required: true, schema: { type: 'number', minimum: -180, maximum: 180 } }, WeatherProvider: { in: 'query', name: 'provider', schema: { type: 'string', example: 'open-meteo' } }, MarketProvider: { in: 'query', name: 'provider', schema: { type: 'string', example: 'agmarknet' } }, Commodity: { in: 'query', name: 'commodity', schema: { type: 'string', example: 'wheat' } }, State: { in: 'query', name: 'state', schema: { type: 'string', example: 'Haryana' } }, District: { in: 'query', name: 'district', schema: { type: 'string', example: 'Karnal' } }, Market: { in: 'query', name: 'market', schema: { type: 'string' } }, Limit: { in: 'query', name: 'limit', schema: { type: 'integer', minimum: 1, maximum: 100, default: 50 } }, Offset: { in: 'query', name: 'offset', schema: { type: 'integer', minimum: 0, default: 0 } }
    },
    schemas: {
      Meta: { type: 'object', required: ['timestamp', 'requestId'], properties: { timestamp: { type: 'string', format: 'date-time' }, requestId: { type: 'string' }, provider: { type: 'string' }, cache: { enum: ['hit', 'miss'] }, pagination: { type: 'object' } } },
      Error: { type: 'object', required: ['code', 'message'], properties: { code: { type: 'string' }, message: { type: 'string' }, details: { type: 'array', items: { type: 'object' } } } },
      Health: { type: 'object', properties: { status: { example: 'ok' }, service: { type: 'string' }, version: { example: 'v1' }, providers: { type: 'array', items: { $ref: '#/components/schemas/Provider' } } } },
      Provider: { type: 'object', required: ['id', 'domain', 'capabilities', 'status'], properties: { id: { type: 'string' }, domain: { type: 'string', enum: ['weather', 'markets', 'satellite'] }, capabilities: { type: 'array', items: { type: 'string' } }, status: { type: 'object', properties: { configured: { type: 'boolean' }, available: { type: 'boolean' }, authentication: { type: 'string' } } } } },
      Location: { type: 'object', properties: { country: { example: 'IN' }, state: { nullable: true, type: 'string' }, district: { nullable: true, type: 'string' }, market: { nullable: true, type: 'string' }, latitude: { nullable: true, type: 'number' }, longitude: { nullable: true, type: 'number' } } },
      CurrentWeather: { type: 'object', properties: { location: { $ref: '#/components/schemas/Location' }, observedAt: { type: 'string' }, temperatureC: { type: 'number' }, condition: { type: 'object' } } },
      ForecastDay: { type: 'object', properties: { date: { type: 'string', format: 'date' }, temperature: { type: 'object' }, precipitation: { type: 'object' }, wind: { type: 'object' }, condition: { type: 'object' } } },
      MarketPrice: { type: 'object', properties: { id: { type: 'string' }, commodity: { type: 'object', properties: { name: { type: 'string' }, canonicalName: { type: 'string' } } }, variety: { nullable: true, type: 'object' }, market: { type: 'object', properties: { name: { type: 'string' }, location: { $ref: '#/components/schemas/Location' } } }, price: { type: 'object', properties: { minimumInrPerQuintal: { nullable: true, type: 'number' }, maximumInrPerQuintal: { nullable: true, type: 'number' }, modalInrPerQuintal: { type: 'number' }, unit: { type: 'object' } } }, arrivalDate: { nullable: true, type: 'string', format: 'date' }, source: { type: 'object' } } },
      CropInput: { type: 'object', required: ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], properties: { N: { type: 'number' }, P: { type: 'number' }, K: { type: 'number' }, temperature: { type: 'number' }, humidity: { type: 'number' }, ph: { type: 'number' }, rainfall: { type: 'number' } } },
      CropRecommendation: { type: 'object', required: ['recommendedCrop', 'method', 'fallbackUsed', 'provenance'], properties: { recommendedCrop: { type: 'string' }, recommendation: { type: 'string' }, crop: { type: 'string' }, confidencePercent: { nullable: true, type: 'number' }, method: { type: 'string', enum: ['ml_model', 'rule_based', 'unknown'] }, fallbackUsed: { type: 'boolean' }, model: { nullable: true, type: 'object' }, provenance: { type: 'object' } } },
      PlantDiagnosis: { type: 'object', properties: { status: { type: 'string', enum: ['success'] }, disease: { type: 'string' }, confidencePercent: { nullable: true, type: 'number' }, model: { nullable: true, type: 'object' }, provenance: { type: 'object' } } },
      AdvisoryInput: { type: 'object', required: ['farm'], properties: { farm: { $ref: '#/components/schemas/Farm' }, crop: { nullable: true, type: 'object' }, location: { nullable: true, $ref: '#/components/schemas/Location' }, weather: { nullable: true, $ref: '#/components/schemas/CurrentWeather' }, provider: { type: 'string', example: 'open-meteo' } } },
      Farm: { type: 'object', required: ['id', 'name', 'area'], properties: { id: { type: 'string' }, name: { type: 'string' }, location: { $ref: '#/components/schemas/Location' }, boundary: { $ref: '#/components/schemas/GeoJSONBoundary' }, area: { type: 'object', required: ['value', 'unit'], properties: { value: { type: 'number', minimum: 0, exclusiveMinimum: true }, unit: { type: 'string', enum: ['acre', 'hectare'] } } }, soil: { nullable: true, type: 'object' }, currentCrop: { nullable: true, type: 'object' }, sowingDate: { nullable: true, type: 'string', format: 'date' }, irrigation: { nullable: true, type: 'object' }, metadata: { type: 'object' } } },
      GeoJSONBoundary: { type: 'object', required: ['type', 'coordinates'], properties: { type: { type: 'string', enum: ['Polygon', 'MultiPolygon'] }, coordinates: { type: 'array' } } },
      FieldHealth: { type: 'object', required: ['status', 'provider'], properties: { status: { type: 'string', enum: ['ok', 'low_quality', 'unavailable'] }, observation: { nullable: true, type: 'object' }, trend: { nullable: true, type: 'object' }, observations: { type: 'array' }, provider: { type: 'object' }, reason: { type: 'string' } } },
      AlertRule: { type: 'object', required: ['id', 'type'], properties: { id: { type: 'string' }, type: { type: 'string', enum: ['heavy_rain', 'temperature_threshold', 'market_price_threshold', 'vegetation_decline', 'stale_observation'] }, severity: { type: 'string', enum: ['info', 'warning', 'critical'] }, threshold: { type: 'number' }, operator: { type: 'string' }, commodity: { type: 'string' }, maxAgeDays: { type: 'number' } } },
      Alert: { type: 'object', required: ['id', 'ruleId', 'severity', 'trigger', 'source', 'timestamp'], properties: { id: { type: 'string' }, ruleId: { type: 'string' }, severity: { type: 'string' }, trigger: { type: 'object' }, source: { type: 'string' }, timestamp: { type: 'string', format: 'date-time' }, message: { type: 'string' } } },
      AlertEvaluation: { type: 'object', properties: { alerts: { type: 'array', items: { $ref: '#/components/schemas/Alert' } }, evaluatedAt: { type: 'string', format: 'date-time' } } },
      Advisory: { type: 'object', required: ['id', 'severity', 'title', 'message', 'reasons', 'basis'], properties: { id: { type: 'string' }, severity: { type: 'string', enum: ['info', 'low', 'medium', 'high'] }, title: { type: 'string' }, message: { type: 'string' }, reasons: { type: 'array', items: { type: 'string' } }, basis: { type: 'string' } } },
      AdvisoryResult: { type: 'object', properties: { advisories: { type: 'array', items: { $ref: '#/components/schemas/Advisory' } }, context: { type: 'object' }, provenance: { type: 'object', properties: { engine: { type: 'string' }, version: { type: 'string' }, sources: { type: 'array', items: { type: 'object' } } } } } }
    }
  }
};

module.exports = { openApiDocument };
